
using System;

public class CryptoCurrencyModel
{
    public string id { get; set; }
    public string symbol { get; set; }
    public string name { get; set; }
    public object asset_platform_id { get; set; }
    public Platforms platforms { get; set; }
    public float block_time_in_minutes { get; set; }
    public string hashing_algorithm { get; set; }
    public string[] categories { get; set; }
    public object public_notice { get; set; }
    public object[] additional_notices { get; set; }
    public Description description { get; set; }
    public Links links { get; set; }
    public Image image { get; set; }
    public string country_origin { get; set; }
    public string genesis_date { get; set; }
    public float sentiment_votes_up_percentage { get; set; }
    public float sentiment_votes_down_percentage { get; set; }
    public float market_cap_rank { get; set; }
    public float coingecko_rank { get; set; }
    public float coingecko_score { get; set; }
    public float developer_score { get; set; }
    public float community_score { get; set; }
    public float liquidity_score { get; set; }
    public float public_floaterest_score { get; set; }
    public Market_Data market_data { get; set; }
    public Public_floaterest_Stats public_floaterest_stats { get; set; }
    public object[] status_updates { get; set; }
    public DateTime last_updated { get; set; }
}

public class Platforms
{
    public string _ { get; set; }
}

public class Description
{
    public string en { get; set; }
}

public class Links
{
    public string[] homepage { get; set; }
    public string[] blockchain_site { get; set; }
    public string[] official_forum_url { get; set; }
    public string[] chat_url { get; set; }
    public string[] announcement_url { get; set; }
    public string twitter_screen_name { get; set; }
    public string facebook_username { get; set; }
    public object bitcofloatalk_thread_identifier { get; set; }
    public string telegram_channel_identifier { get; set; }
    public string subreddit_url { get; set; }
    public Repos_Url repos_url { get; set; }
}

public class Repos_Url
{
    public string[] github { get; set; }
    public object[] bitbucket { get; set; }
}

public class Image
{
    public string thumb { get; set; }
    public string small { get; set; }
    public string large { get; set; }
}

public class Market_Data
{
    public Current_Price current_price { get; set; }
    public object total_value_locked { get; set; }
    public object mcap_to_tvl_ratio { get; set; }
    public object fdv_to_tvl_ratio { get; set; }
    public object roi { get; set; }
    public Ath ath { get; set; }
    public Ath_Change_Percentage ath_change_percentage { get; set; }
    public Ath_Date ath_date { get; set; }
    public Atl atl { get; set; }
    public Atl_Change_Percentage atl_change_percentage { get; set; }
    public Atl_Date atl_date { get; set; }
    public Market_Cap market_cap { get; set; }
    public float market_cap_rank { get; set; }
    public Fully_Diluted_Valuation fully_diluted_valuation { get; set; }
    public Total_Volume total_volume { get; set; }
    public High_24H high_24h { get; set; }
    public Low_24H low_24h { get; set; }
    public float price_change_24h { get; set; }
    public float price_change_percentage_24h { get; set; }
    public float price_change_percentage_7d { get; set; }
    public float price_change_percentage_14d { get; set; }
    public float price_change_percentage_30d { get; set; }
    public float price_change_percentage_60d { get; set; }
    public float price_change_percentage_200d { get; set; }
    public float price_change_percentage_1y { get; set; }
    public float market_cap_change_24h { get; set; }
    public float market_cap_change_percentage_24h { get; set; }
    public Price_Change_24H_In_Currency price_change_24h_in_currency { get; set; }
    public Price_Change_Percentage_1H_In_Currency price_change_percentage_1h_in_currency { get; set; }
    public Price_Change_Percentage_24H_In_Currency price_change_percentage_24h_in_currency { get; set; }
    public Price_Change_Percentage_7D_In_Currency price_change_percentage_7d_in_currency { get; set; }
    public Price_Change_Percentage_14D_In_Currency price_change_percentage_14d_in_currency { get; set; }
    public Price_Change_Percentage_30D_In_Currency price_change_percentage_30d_in_currency { get; set; }
    public Price_Change_Percentage_60D_In_Currency price_change_percentage_60d_in_currency { get; set; }
    public Price_Change_Percentage_200D_In_Currency price_change_percentage_200d_in_currency { get; set; }
    public Price_Change_Percentage_1Y_In_Currency price_change_percentage_1y_in_currency { get; set; }
    public Market_Cap_Change_24H_In_Currency market_cap_change_24h_in_currency { get; set; }
    public Market_Cap_Change_Percentage_24H_In_Currency market_cap_change_percentage_24h_in_currency { get; set; }
    public float total_supply { get; set; }
    public float max_supply { get; set; }
    public float circulating_supply { get; set; }
    public DateTime last_updated { get; set; }
}

public class Current_Price
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Ath
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public long vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Ath_Change_Percentage
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Ath_Date
{
    public DateTime aed { get; set; }
    public DateTime ars { get; set; }
    public DateTime aud { get; set; }
    public DateTime bch { get; set; }
    public DateTime bdt { get; set; }
    public DateTime bhd { get; set; }
    public DateTime bmd { get; set; }
    public DateTime bnb { get; set; }
    public DateTime brl { get; set; }
    public DateTime btc { get; set; }
    public DateTime cad { get; set; }
    public DateTime chf { get; set; }
    public DateTime clp { get; set; }
    public DateTime cny { get; set; }
    public DateTime czk { get; set; }
    public DateTime dkk { get; set; }
    public DateTime dot { get; set; }
    public DateTime eos { get; set; }
    public DateTime eth { get; set; }
    public DateTime eur { get; set; }
    public DateTime gbp { get; set; }
    public DateTime hkd { get; set; }
    public DateTime huf { get; set; }
    public DateTime idr { get; set; }
    public DateTime ils { get; set; }
    public DateTime inr { get; set; }
    public DateTime jpy { get; set; }
    public DateTime krw { get; set; }
    public DateTime kwd { get; set; }
    public DateTime lkr { get; set; }
    public DateTime ltc { get; set; }
    public DateTime mmk { get; set; }
    public DateTime mxn { get; set; }
    public DateTime myr { get; set; }
    public DateTime ngn { get; set; }
    public DateTime nok { get; set; }
    public DateTime nzd { get; set; }
    public DateTime php { get; set; }
    public DateTime pkr { get; set; }
    public DateTime pln { get; set; }
    public DateTime rub { get; set; }
    public DateTime sar { get; set; }
    public DateTime sek { get; set; }
    public DateTime sgd { get; set; }
    public DateTime thb { get; set; }
    public DateTime _try { get; set; }
    public DateTime twd { get; set; }
    public DateTime uah { get; set; }
    public DateTime usd { get; set; }
    public DateTime vef { get; set; }
    public DateTime vnd { get; set; }
    public DateTime xag { get; set; }
    public DateTime xau { get; set; }
    public DateTime xdr { get; set; }
    public DateTime xlm { get; set; }
    public DateTime xrp { get; set; }
    public DateTime yfi { get; set; }
    public DateTime zar { get; set; }
    public DateTime bits { get; set; }
    public DateTime link { get; set; }
    public DateTime sats { get; set; }
}

public class Atl
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Atl_Change_Percentage
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Atl_Date
{
    public DateTime aed { get; set; }
    public DateTime ars { get; set; }
    public DateTime aud { get; set; }
    public DateTime bch { get; set; }
    public DateTime bdt { get; set; }
    public DateTime bhd { get; set; }
    public DateTime bmd { get; set; }
    public DateTime bnb { get; set; }
    public DateTime brl { get; set; }
    public DateTime btc { get; set; }
    public DateTime cad { get; set; }
    public DateTime chf { get; set; }
    public DateTime clp { get; set; }
    public DateTime cny { get; set; }
    public DateTime czk { get; set; }
    public DateTime dkk { get; set; }
    public DateTime dot { get; set; }
    public DateTime eos { get; set; }
    public DateTime eth { get; set; }
    public DateTime eur { get; set; }
    public DateTime gbp { get; set; }
    public DateTime hkd { get; set; }
    public DateTime huf { get; set; }
    public DateTime idr { get; set; }
    public DateTime ils { get; set; }
    public DateTime inr { get; set; }
    public DateTime jpy { get; set; }
    public DateTime krw { get; set; }
    public DateTime kwd { get; set; }
    public DateTime lkr { get; set; }
    public DateTime ltc { get; set; }
    public DateTime mmk { get; set; }
    public DateTime mxn { get; set; }
    public DateTime myr { get; set; }
    public DateTime ngn { get; set; }
    public DateTime nok { get; set; }
    public DateTime nzd { get; set; }
    public DateTime php { get; set; }
    public DateTime pkr { get; set; }
    public DateTime pln { get; set; }
    public DateTime rub { get; set; }
    public DateTime sar { get; set; }
    public DateTime sek { get; set; }
    public DateTime sgd { get; set; }
    public DateTime thb { get; set; }
    public DateTime _try { get; set; }
    public DateTime twd { get; set; }
    public DateTime uah { get; set; }
    public DateTime usd { get; set; }
    public DateTime vef { get; set; }
    public DateTime vnd { get; set; }
    public DateTime xag { get; set; }
    public DateTime xau { get; set; }
    public DateTime xdr { get; set; }
    public DateTime xlm { get; set; }
    public DateTime xrp { get; set; }
    public DateTime yfi { get; set; }
    public DateTime zar { get; set; }
    public DateTime bits { get; set; }
    public DateTime link { get; set; }
    public DateTime sats { get; set; }
}

public class Market_Cap
{
    public long aed { get; set; }
    public long ars { get; set; }
    public long aud { get; set; }
    public float bch { get; set; }
    public long bdt { get; set; }
    public long bhd { get; set; }
    public long bmd { get; set; }
    public long bnb { get; set; }
    public long brl { get; set; }
    public float btc { get; set; }
    public long cad { get; set; }
    public long chf { get; set; }
    public long clp { get; set; }
    public long cny { get; set; }
    public long czk { get; set; }
    public long dkk { get; set; }
    public long dot { get; set; }
    public long eos { get; set; }
    public float eth { get; set; }
    public long eur { get; set; }
    public long gbp { get; set; }
    public long hkd { get; set; }
    public long huf { get; set; }
    public long idr { get; set; }
    public long ils { get; set; }
    public long inr { get; set; }
    public long jpy { get; set; }
    public long krw { get; set; }
    public long kwd { get; set; }
    public long lkr { get; set; }
    public long ltc { get; set; }
    public long mmk { get; set; }
    public long mxn { get; set; }
    public long myr { get; set; }
    public long ngn { get; set; }
    public long nok { get; set; }
    public long nzd { get; set; }
    public long php { get; set; }
    public long pkr { get; set; }
    public long pln { get; set; }
    public long rub { get; set; }
    public long sar { get; set; }
    public long sek { get; set; }
    public long sgd { get; set; }
    public long thb { get; set; }
    public long _try { get; set; }
    public long twd { get; set; }
    public long uah { get; set; }
    public long usd { get; set; }
    public long vef { get; set; }
    public long vnd { get; set; }
    public long xag { get; set; }
    public float xau { get; set; }
    public long xdr { get; set; }
    public long xlm { get; set; }
    public long xrp { get; set; }
    public float yfi { get; set; }
    public long zar { get; set; }
    public long bits { get; set; }
    public long link { get; set; }
    public long sats { get; set; }
}

public class Fully_Diluted_Valuation
{
    public long aed { get; set; }
    public long ars { get; set; }
    public long aud { get; set; }
    public float bch { get; set; }
    public long bdt { get; set; }
    public long bhd { get; set; }
    public long bmd { get; set; }
    public long bnb { get; set; }
    public long brl { get; set; }
    public float btc { get; set; }
    public long cad { get; set; }
    public long chf { get; set; }
    public long clp { get; set; }
    public long cny { get; set; }
    public long czk { get; set; }
    public long dkk { get; set; }
    public long dot { get; set; }
    public long eos { get; set; }
    public float eth { get; set; }
    public long eur { get; set; }
    public long gbp { get; set; }
    public long hkd { get; set; }
    public long huf { get; set; }
    public long idr { get; set; }
    public long ils { get; set; }
    public long inr { get; set; }
    public long jpy { get; set; }
    public long krw { get; set; }
    public long kwd { get; set; }
    public long lkr { get; set; }
    public long ltc { get; set; }
    public long mmk { get; set; }
    public long mxn { get; set; }
    public long myr { get; set; }
    public long ngn { get; set; }
    public long nok { get; set; }
    public long nzd { get; set; }
    public long php { get; set; }
    public long pkr { get; set; }
    public long pln { get; set; }
    public long rub { get; set; }
    public long sar { get; set; }
    public long sek { get; set; }
    public long sgd { get; set; }
    public long thb { get; set; }
    public long _try { get; set; }
    public long twd { get; set; }
    public long uah { get; set; }
    public long usd { get; set; }
    public long vef { get; set; }
    public long vnd { get; set; }
    public long xag { get; set; }
    public float xau { get; set; }
    public long xdr { get; set; }
    public long xlm { get; set; }
    public long xrp { get; set; }
    public float yfi { get; set; }
    public long zar { get; set; }
    public long bits { get; set; }
    public long link { get; set; }
    public long sats { get; set; }
}

public class Total_Volume
{
    public long aed { get; set; }
    public long ars { get; set; }
    public long aud { get; set; }
    public float bch { get; set; }
    public long bdt { get; set; }
    public long bhd { get; set; }
    public long bmd { get; set; }
    public float bnb { get; set; }
    public long brl { get; set; }
    public float btc { get; set; }
    public long cad { get; set; }
    public long chf { get; set; }
    public long clp { get; set; }
    public long cny { get; set; }
    public long czk { get; set; }
    public long dkk { get; set; }
    public long dot { get; set; }
    public long eos { get; set; }
    public float eth { get; set; }
    public long eur { get; set; }
    public long gbp { get; set; }
    public long hkd { get; set; }
    public long huf { get; set; }
    public long idr { get; set; }
    public long ils { get; set; }
    public long inr { get; set; }
    public long jpy { get; set; }
    public long krw { get; set; }
    public long kwd { get; set; }
    public long lkr { get; set; }
    public float ltc { get; set; }
    public long mmk { get; set; }
    public long mxn { get; set; }
    public long myr { get; set; }
    public long ngn { get; set; }
    public long nok { get; set; }
    public long nzd { get; set; }
    public long php { get; set; }
    public long pkr { get; set; }
    public long pln { get; set; }
    public long rub { get; set; }
    public long sar { get; set; }
    public long sek { get; set; }
    public long sgd { get; set; }
    public long thb { get; set; }
    public long _try { get; set; }
    public long twd { get; set; }
    public long uah { get; set; }
    public long usd { get; set; }
    public long vef { get; set; }
    public long vnd { get; set; }
    public long xag { get; set; }
    public float xau { get; set; }
    public long xdr { get; set; }
    public long xlm { get; set; }
    public long xrp { get; set; }
    public float yfi { get; set; }
    public long zar { get; set; }
    public long bits { get; set; }
    public long link { get; set; }
    public long sats { get; set; }
}

public class High_24H
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Low_24H
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_24H_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_Percentage_1H_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_Percentage_24H_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_Percentage_7D_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_Percentage_14D_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_Percentage_30D_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_Percentage_60D_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_Percentage_200D_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Price_Change_Percentage_1Y_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Market_Cap_Change_24H_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public long dot { get; set; }
    public long eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public long idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public long mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public long vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public long xlm { get; set; }
    public long xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public long bits { get; set; }
    public long link { get; set; }
    public long sats { get; set; }
}

public class Market_Cap_Change_Percentage_24H_In_Currency
{
    public float aed { get; set; }
    public float ars { get; set; }
    public float aud { get; set; }
    public float bch { get; set; }
    public float bdt { get; set; }
    public float bhd { get; set; }
    public float bmd { get; set; }
    public float bnb { get; set; }
    public float brl { get; set; }
    public float btc { get; set; }
    public float cad { get; set; }
    public float chf { get; set; }
    public float clp { get; set; }
    public float cny { get; set; }
    public float czk { get; set; }
    public float dkk { get; set; }
    public float dot { get; set; }
    public float eos { get; set; }
    public float eth { get; set; }
    public float eur { get; set; }
    public float gbp { get; set; }
    public float hkd { get; set; }
    public float huf { get; set; }
    public float idr { get; set; }
    public float ils { get; set; }
    public float inr { get; set; }
    public float jpy { get; set; }
    public float krw { get; set; }
    public float kwd { get; set; }
    public float lkr { get; set; }
    public float ltc { get; set; }
    public float mmk { get; set; }
    public float mxn { get; set; }
    public float myr { get; set; }
    public float ngn { get; set; }
    public float nok { get; set; }
    public float nzd { get; set; }
    public float php { get; set; }
    public float pkr { get; set; }
    public float pln { get; set; }
    public float rub { get; set; }
    public float sar { get; set; }
    public float sek { get; set; }
    public float sgd { get; set; }
    public float thb { get; set; }
    public float _try { get; set; }
    public float twd { get; set; }
    public float uah { get; set; }
    public float usd { get; set; }
    public float vef { get; set; }
    public float vnd { get; set; }
    public float xag { get; set; }
    public float xau { get; set; }
    public float xdr { get; set; }
    public float xlm { get; set; }
    public float xrp { get; set; }
    public float yfi { get; set; }
    public float zar { get; set; }
    public float bits { get; set; }
    public float link { get; set; }
    public float sats { get; set; }
}

public class Public_floaterest_Stats
{
    public float alexa_rank { get; set; }
    public object bing_matches { get; set; }
}
